# Generated by Django 3.1.2 on 2020-10-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Patches', 'Patches'), ('Stickers', 'Stickers'), ('Hats', 'Hats'), ('WaterBottle', 'WaterBottle')], max_length=20, null=True),
        ),
    ]
