# Generated by Django 3.1.2 on 2020-11-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201026_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
