# Generated by Django 3.1.2 on 2020-10-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('challenge_description', models.TextField()),
                ('challenge_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('challenge_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('challenge_distance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('challenge_difficulty_rating', models.CharField(choices=[('Easy', 'Easy, all levels of fitness and beginners'), ('Medium', 'Medium, fair level of fitness, some steep climbs'), ('Hard', 'Challenging, good level of fitness and experience needed')], default='Medium', max_length=20)),
                ('challenge_ascent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('challenge_descent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('challenge_estimate_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('challenge_award_name', models.CharField(max_length=254)),
                ('challenge_notes', models.TextField(blank=True, null=True)),
                ('challenge_location', models.CharField(max_length=254)),
                ('challenge_start_point', models.CharField(max_length=254)),
                ('challenge_carpark', models.CharField(max_length=254)),
                ('Route_Step_1', models.TextField()),
                ('Route_Step_2', models.TextField(blank=True, null=True)),
                ('Route_Step_3', models.TextField(blank=True, null=True)),
                ('Route_Step_4', models.TextField(blank=True, null=True)),
                ('Route_Step_5', models.TextField(blank=True, null=True)),
                ('Route_Step_6', models.TextField(blank=True, null=True)),
                ('Route_Step_7', models.TextField(blank=True, null=True)),
                ('Route_Step_8', models.TextField(blank=True, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('recommended_map', models.CharField(max_length=254)),
            ],
        ),
    ]
